import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: "--font-roboto",
  subsets: ['latin'],
})

const fontInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={cn(roboto.variable, fontInter.variable)}>
      <div className="min-h-screen flex flex-col">
        <header>
          <nav className="flex sm:justify-center space-x-4 bg-slate-400 p-4">
            {[
              ['Home', '/dashboard'],
              ['Team', '/team'],
              ['Projects', '/projects'],
              ['Reports', '/reports'],
            ].map(([title, url]) => (
                <a
                    key={title}
                    href={url}
                    className="rounded-lg px-3 py-2 text-slate-700 font-medium hover:bg-slate-500 hover:text-slate-900"
                >
                  {title}
                </a>
            ))}
          </nav>
        </header>

        <main className="flex-grow">
          {children}

        </main>
        <footer className="bg-slate-400 p-4">
          <div className="table w-full">
            <div className="table-header-group">
              <div className="table-row">
                <div className="table-cell text-left">Company</div>
                <div className="table-cell text-left">Link</div>
                <div className="table-cell text-left">Menubar</div>
              </div>
            </div>
            <div className="table-row-group">
              <div className="table-row">
                <div className="table-cell">Nextbit Studio</div>
                <div className="table-cell">Facebook</div>
                <div className="table-cell">Home</div>
              </div>
              <div className="table-row">
                <div className="table-cell">Address: Mirpur Dohs</div>
                <div className="table-cell">Insta</div>
                <div className="table-cell">Image</div>
              </div>
              <div className="table-row">
                <div className="table-cell">Contact: 016101****</div>
                <div className="table-cell">Slack</div>
                <div className="table-cell">Contact</div>
              </div>
            </div>
          </div>
        </footer>
      </div>
      </body>
      </html>
  );
}
